# Generated by Django 5.2.7 on 2025-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='known_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
