# Generated by Django 5.2.7 on 2025-11-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_known_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='known_keywords',
        ),
    ]
