# Generated by Django 5.2.7 on 2025-11-28 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_known_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
