# Generated by Django 5.2.7 on 2025-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordexplanationpair',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
